server:
  port: 8089

spring:
  security:
    oauth2:
      client:
        registration:
          login-client:
            provider: local-authz
            client-id: client-1234
            client-secret: secret
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            scope: profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Login Client
        provider:
          local-authz:
            authorization-uri: http://localhost:8090/oauth/authorize
            token-uri: http://localhost:8090/oauth/token
            user-info-uri: http://localhost:8090/resources/userinfo
            user-name-attribute: name